import Image from "next/image";

export const metadata = {
    title: "Gallery",
    description: "Generated by Gallery",
};
const Gallery = () => {
    return (
        <div className="mt-2">
            <Image alt="new year" loading="lazy" width={800} height={800} className="mx-auto" src="https://img.pikbest.com/templates/20241111/2025-happy-new-year-celebration-web-banner-post-template_11065161.jpg!bw700" />
        </div>
    );
};

export default Gallery;